[package]
name = "zagreus-generator"
version = "0.0.5"
authors = ["Mario Kaufmann <mario.kaufmann@bluemail.ch>"]
edition = "2021"

[dependencies]
anyhow = "1.0.56"
log = "0.4.16"
reqwest = { version = "0.11.10", features = ["blocking", "multipart"] }
serde = "1.0.136"
serde_derive = "1.0.136"
serde_json = "1.0.79"
serde_yaml = "0.8.23"
xml-rs = "0.8.4"
zip = "0.6.1"
walkdir = "2.3.2"
structopt = "0.3.26"
notify = "4.0.17"

[dependencies.log4rs]
version = "1.0.0"
default-features = false
features = ["console_appender"]

[dev-dependencies]
rand = "0.8.5"
