[package]
name = "zagreus-server"
version = "0.0.5"
authors = ["Mario Kaufmann <mario.kaufmann@bluemail.ch>"]
edition = "2021"

[dependencies]
anyhow = "1.0.57"
axum = { version = "0.5.4", features = ["json", "http1", "http2", "ws", "multipart"]}
axum-server = "0.4.0"
log = "0.4.16"
futures = "0.3.21"
hyper = "0.14.18"
rand = "0.8.5"
serde = "1.0.137"
serde_derive = "1.0.136"
serde_json = "1.0.80"
structopt = "0.3.26"
tokio = { version = "1.18.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1.8"
tower = { version = "0.4.12", features = ["filter"]}
tower-http = { version = "0.3.2", features = ["fs", "trace"]}
zip = "0.6.2"

[dependencies.log4rs]
version = "1.1.1"
default-features = false
features = ["console_appender", "rolling_file_appender", "fixed_window_roller", "size_trigger", "compound_policy"]

[dev-dependencies]
tokio-tungstenite = "0.17.1"
tungstenite = "0.17.2"
