[package]
name = "zagreus-server"
version = "0.0.4"
authors = ["Mario Kaufmann <mario.kaufmann@bluemail.ch>"]
edition = "2021"

[dependencies]
axum = { version = "0.4.4", features = ["json", "http1", "http2", "ws", "multipart"]}
axum-server = "0.3.3"
log = "0.4.14"
futures = "0.3.19"
hyper = "0.14.16"
rand = "0.8.4"
serde = "1.0.135"
serde_derive = "1.0.135"
serde_json = "1.0.78"
structopt = "0.3.26"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread", "sync", "time"] }
tokio-stream = "0.1.8"
tower = { version = "0.4.11", features = ["filter"]}
tower-http = { version = "0.2.1", features = ["fs", "trace"]}
zip = "0.5.13"

[dependencies.log4rs]
version = "1.0.0"
default-features = false
features = ["console_appender", "rolling_file_appender", "fixed_window_roller", "size_trigger", "compound_policy"]

[dev-dependencies]
tokio-tungstenite = "0.16.1"
tungstenite = "0.16.0"
