[package]
name = "zagreus-server"
version = "0.1.0"
authors = ["Mario Kaufmann <mario.kaufmann@bluemail.ch>"]
edition = "2018"

[dependencies]
log = "0.4.11"
futures = "0.3.8"
hyper = "0.13.9"
rand = "0.7.3"
serde = "1.0.117"
serde_derive = "1.0.117"
serde_json = "1.0.59"
tokio = { version = "0.2.23", features = ["macros", "rt-threaded", "stream", "sync", "time"] }
warp = "0.2.5"
zip = "0.5.8"

[dependencies.log4rs]
version = "0.13.0"
default-features = false
features = ["console_appender", "rolling_file_appender", "fixed_window_roller", "size_trigger", "compound_policy"]

[dev-dependencies]
tokio-tungstenite = "0.12.0"
tungstenite = "0.11.1"