name: build
on: [push]
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: Build zagreus runtime
        run: |
          npm ci --no-optional
          npm run build
        working-directory: ./zagreus-runtime
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build zagreus generator
        run: cargo build --release
        working-directory: ./zagreus-generator
      - name: Test zagreus generator
        run: cargo test
        working-directory: ./zagreus-generator
      - name: Lint zagreus generator
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings
        working-directory: ./zagreus-generator
      - name: Build zagreus server
        run: cargo build --release
        working-directory: ./zagreus-server
      - name: Test zagreus server
        run: cargo test
        working-directory: ./zagreus-server
      - name: Lint zagreus server
        run: |
          rustup component add clippy
          cargo clippy -- -D warnings
        working-directory: ./zagreus-server